# Generated by Django 6.0.3 on 2026-04-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='contacts_surname_a7f954_idx',
            old_name='contacts_co_surname_ba74da_idx',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
    ]
