# Generated by Django 6.0.3 on 2026-04-02 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('contacts', '0002_rename_contacts_co_surname_ba74da_idx_contacts_surname_a7f954_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='clients',
            field=models.ManyToManyField(blank=True, help_text='Clients linked to this contact', related_name='contacts', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Contact email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Contact first name', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='surname',
            field=models.CharField(help_text='Contact last name', max_length=255),
        ),
    ]
