# Generated by Django 6.0.3 on 2026-04-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name', max_length=255)),
                ('client_code', models.CharField(blank=True, editable=False, help_text='Auto-generated unique client code', max_length=6, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['client_code'], name='clients_client__c596c4_idx')],
            },
        ),
    ]
